### ISSUE TITLE
Practica7

### ISSUE THREAD

**Issue by GibranVasquez** [SistemasTecTlaxiaco/actividad-7-practica-de-entrevista-team-gbkn#1]
[Practica 8.pdf](https://github.com/user-attachments/files/17562602/Practica.8.pdf)

**Comment by josealfredo79** [comment]
Calificacion...????

**Comment by AricelCastro** [comment]
29/30 faltaron mas ilustraciones

**Comment by josealfredo79** [comment]
bien hecho y revisado...
